version: '3'
services:
  database:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=doodle_chat
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  database-data: