version: '3'
services:
  doodle-chat-api:
    container_name: doodle-chat-api
    build: ./server
    ports:
      - 8080:8080
    environment:
      DB_HOST: database:5432
      PORT: 8080
    depends_on:
      - database
    links:
      - database

  database:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=doodle_chat
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  database-data: